//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalShow_4th_HandIn {
	
	
	public partial class Act {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button GoToOverview;
		
		protected System.Web.UI.WebControls.TextBox TextBoxTitle;
		
		protected System.Web.UI.WebControls.Label LabelTitle;
		
		protected System.Web.UI.WebControls.TextBox TextBoxShortDescription;
		
		protected System.Web.UI.WebControls.Label LabelShortDescription;
		
		protected System.Web.UI.WebControls.TextBox TextBoxDuration;
		
		protected System.Web.UI.WebControls.Label LabelDuration;
		
		protected System.Web.UI.WebControls.TextBox TextBoxPicLink;
		
		protected System.Web.UI.WebControls.Label LabelPicLink;
		
		protected System.Web.UI.WebControls.Image ActImage;
		
		protected System.Web.UI.WebControls.Label LabelActImage;
		
		protected System.Web.UI.WebControls.Button ButtonAdd;
		
		protected System.Web.UI.WebControls.Button ButtonEdit;
		
		protected System.Web.UI.WebControls.Label LabelError;
		
		protected System.Web.UI.WebControls.FileUpload ImageUpload;
		
		protected System.Web.UI.WebControls.Label LabelImageUpload;
		
		protected System.Web.UI.WebControls.Button ButtonImage;
		
		protected System.Web.UI.WebControls.DataList dtlist;
		
		protected System.Web.UI.WebControls.Image Image1;
		
		protected System.Web.UI.WebControls.Label Label1;
	}
}
