//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalShow_4th_HandIn {
	
	
	public partial class Overview {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Button buttonNewAct;
		
		protected System.Web.UI.WebControls.Button buttonNewProfile;
		
		protected System.Web.UI.WebControls.Button logOut;
		
		protected System.Web.UI.WebControls.ListBox Profiles;
		
		protected System.Web.UI.WebControls.ListBox Acts;
		
		protected System.Web.UI.WebControls.Button buttonEditProfile;
		
		protected System.Web.UI.WebControls.Button buttonDeleteProfile;
		
		protected System.Web.UI.WebControls.Button buttonEditAct;
		
		protected System.Web.UI.WebControls.Button buttonDeleteAct;
		
		protected System.Web.UI.WebControls.Button buttonMoveUp;
		
		protected System.Web.UI.WebControls.Button buttonMoveDown;
	}
}
